import { BuildNavigation } from './../nav';
import { activateBuildItems } from './../item';
import { buildSlider, removeControls } from './../slider';
import {LightBox} from './../lightbox';
import { LazyLoadingActivation } from './../lazyload';
window.lightbox  = LightBox();
window.buildSlider = buildSlider;
window.activateBuildItems = activateBuildItems;
window.removeControls = removeControls;
window.buildNavigation = BuildNavigation;
window.lazyLoadActivation = LazyLoadingActivation;
import './../../css/clientsite.css';